<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class Users extends Seeder
{
    public function run()
    {
        $user = [
            [
                'nik' => 3571010412760003,
                'nama' => 'Agung Wahyudi',
                'tempat_lahir' => 'Kediri',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1976-12-04')),
                'alamat'     => 'Jl. Pringgodani No. 81 Mrican',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'admin',
                'foto' => 'Agung.jpg',
                'jabatan_id' => 7,
                'bidang_id' => 0
            ],
            [
                'nik' => 3506220101610010,
                'nama' => 'Imam Sururi',
                'tempat_lahir' => 'Kediri',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1961-01-01')),
                'alamat'     => 'DSN. SAMBIREJO, RT:05/RW:01, Kel. Tiron, Kec.Banyakan',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'mandor',
                'foto' => 'Imam.jpeg',
                'jabatan_id' => 5,
                'bidang_id' => 3,
            ],
            [
                'nik' => 3504050606790003,
                'nama' => 'Suryono',
                'tempat_lahir' => 'Tulungagung',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1979-06-06')),
                'alamat'     => 'DSN. Sanan',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'pelaksana',
                'foto' => 'Suryono.jpeg',
                'jabatan_id' => 3,
                'bidang_id' => 3,
            ],
            [
                'nik' => 3571010602680010,
                'nama' => 'Sutiyono',
                'tempat_lahir' => 'Nganjuk',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1968-02-06')),
                'alamat'     => 'Jl. Pringgodani No. 8',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'pelaksana',
                'foto' => 'Sutiyono.jpeg',
                'jabatan_id' => 3,
                'bidang_id' => 3,
            ],
            [
                'nik' => 3506220104920001,
                'nama' => 'Andrian Prasetyo',
                'tempat_lahir' => 'Kediri',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1992-04-01')),
                'alamat'     => 'DSN. Manukan',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'tukang',
                'foto' => 'Andrian.jpeg',
                'jabatan_id' => 1,
                'bidang_id' => 1,
            ],
            [
                'nik' => 3506131201910004,
                'nama' => 'Puji Santoso',
                'tempat_lahir' => 'Kediri',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1981-01-12')),
                'alamat'     => 'DSN. Kleponan',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'tukang',
                'foto' => 'Puji.jpeg',
                'jabatan_id' => 1,
                'bidang_id' => 2,
            ],
            [
                'nik' => 3506011303800001,
                'nama' => 'Samiaji',
                'tempat_lahir' => 'Kediri',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1980-03-13')),
                'alamat'     => 'Jl. Bagruk',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'tukang',
                'foto' => 'Samiaji.jpeg',
                'jabatan_id' => 2,
                'bidang_id' => 3,
            ],
            [
                'nik' => 3506111504610002,
                'nama' => 'Kuswandi',
                'tempat_lahir' => 'Kediri',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1961-04-15')),
                'alamat'     => 'DSN. Wonorejo',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'tukang',
                'foto' => 'Kuswandi.jpeg',
                'jabatan_id' => 2,
                'bidang_id' => 3,
            ],
            [
                'nik' => 3571022903830003,
                'nama' => 'Eko Joko Prasetyo',
                'tempat_lahir' => 'Kediri',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1983-03-29')),
                'alamat'     => 'Jl. Banjaran I/51',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'tukang',
                'foto' => 'Eko.jpeg',
                'jabatan_id' => 1,
                'bidang_id' => 3,
            ],
            [
                'nik' => 3518061012700002,
                'nama' => 'Kurnia',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1969-10-10')),
                'alamat'     => 'Jl. Sersan Bahrun No.16',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'tukang',
                'foto' => 'Kurnia.jpeg',
                'jabatan_id' => 2,
                'bidang_id' => 3,
            ],
            [
                'nik' => 3506132111710001,
                'nama' => 'Wijianto',
                'tempat_lahir' => 'Kediri',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1971-11-21')),
                'alamat'     => 'DSN. Bedrek Utara',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'tukang',
                'foto' => 'Wijianto.jpeg',
                'jabatan_id' => 4,
                'bidang_id' => 3,
            ],
            [
                'nik' => 3506220404700002,
                'nama' => 'Jaelani',
                'tempat_lahir' => 'Nganjuk',
                'tanggal_lahir' => date('Y-m-d ', strtotime('1969-04-04')),
                'alamat'     => 'DSN. Manukan',
                'password' => password_hash('12345678', PASSWORD_DEFAULT),
                'role' => 'tukang',
                'foto' => 'Jaelani.jpeg',
                'jabatan_id' => 2,
                'bidang_id' => 3,
            ],
        ];

        $this->db->table('users')->insertBatch($user);
    }
}